<!DOCTYPE html>
<html lang="tr">
<head>
    <link rel="stylesheet" type="text/css" href="../user/style.css">
    <meta charset="utf-8">
    <title> </title>
</head>
<body>
<?  require __DIR__ . "/../views/header-menu.phtml"; ?>
<form method="post" action="siparisonay" name="frmOrderDetails">
<table style="text-align: center" >
    <tr>
        <td>Adres:<textarea name="address" rows="10" cols="20"></textarea></td>
    </tr>
    <tr>
        <td><input type="submit" value="Siparişi Onayla"> </td>
    </tr>
</table>
</form>
</body>
</html>



