<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
</head>
<body>
    <ul style="list-style-type:none">
        <li style="display:inline;"> <a href="/admin/list-orders">Sipariş Listesi</a> </li>
        <li style="display: inline;"> <a href="/admin/list-customers">Müşteri Listesi</a> </li>
        <li style="display: inline;"> <a href="/admin/list-new-orders">Yeni Sipariş Listesi</a> </li>

    </ul>
    <h1> Ürün Listeniz </h1>
    <table width="80%" style="border-collapse: collapse" border="1" cellspacing="0" cellpadding="5">
        <tr>
            <th> Count</th>
            <th> Category</th>
            <th> Gender for Product </th>
            <th> Name</th>
            <th> Size</th>
            <th> Quantity</th>
            <th> Color</th>
            <th> Image URL</th>
            <th> Price</th>
            <th> Actions</th>
        </tr>
        <?  foreach($products as $key => $product) { ?>
            <tr>
                <td><?= $key + 1 ?></td>
                <td><?= $product->category ?></td>
                <td><?= $product->gender ?></td>
                <td><?= $product->name ?></td>
                <td><?= $product->size ?></td>
                <td><?= $product->quantity ?></td>
                <td><?= $product->color ?></td>
                <td><?= $product->imageurl ?></td>
                <td><?= $product->price ?></td>
                <td><a href="/admin/update-products?id=<?= $product->id ?>">Update</a> <a href="/admin/delete-products?id=<?= $product->id ?>">Delete</a></td>
            </tr>
        <?  } ?>
        <tr>
            <td  colspan="10" align="right"><a href="/admin/insert-products">Yeni Ekle</a></td>
        </tr>


    </table><br><br>
</body>
</html>