<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8">
</head>
<body>
<h1> Ürün Güncelleme Sayfası </h1>
<form name="formupdate" method="post" action="/admin/update-products">
    <input type="hidden" name="id" value="<?= $product->id ?>"/>
    Kategori : <select name="kategori">
        <option name="tisort" value="TShirt" <?= $product->category =="TShirt" ? 'selected="selected"' : ''  ?>>TShirt</option>
        <option name="sort" value="Şort" <?= $product->category =="Şort" ? 'selected="selected"' : ''  ?>>Şort</option>
        <option name="gomlek" value="Gömlek"<?= $product->category =="Gömlek" ? 'selected="selected"' : ''  ?>>Gömlek</option>
        <option name="elbise" value="Elbise" <?= $product->category =="Elbise" ? 'selected="selected"' : ''  ?>>Elbise</option>
        <option name="ayakkabi" value="Ayakkabı" <?= $product->category == "Ayakkabı" ? 'selected="selected"' : ''  ?>>Ayakkabı</option>
        <option name="corap" value="Çorap"<?= $product->category =="Çorap" ? 'selected="selected"' : ''  ?>>Çorap</option>
        <option name="pantolon" value="Pantolon" <?= $product->category =="Pantolon" ? 'selected="selected"' : ''  ?>>Pantolon</option>
    </select><br><br>
    Kategori : <select name="cinsiyet">
        <option name="bayan" value="bayan" <?= $product->gender =="bayan" ? 'selected="selected"' : ''  ?>>Bayan</option>
        <option name="erkek" value="erkek" <?= $product->gender =="erkek" ? 'selected="selected"' : ''  ?>>Erkek</option>
        <option name="unisex" value="unisex"<?= $product->gender =="unisex" ? 'selected="selected"' : ''  ?>>Unisex</option>
        <option name="genccocuk" value="genccocuk" <?= $product->gender =="genccocuk" ? 'selected="selected"' : ''  ?>>Genç-Çocuk</option>
    </select><br><br>
    Ürün Adı: <input type="text" name="txtName" value="<?= $product->name ?>" /><br><br>
    Beden:  <select name="beden">
        <option name="xsmall" value="XSmall" <? if($product->size =="XSmall") echo 'selected="selected"';  ?>>XSmall</option>
        <option name="small" value="Small" <? if($product->size =="Small") echo 'selected="selected"';  ?> >Small</option>
        <option name="medium" value="Medium" <? if($product->size =="Medium") echo 'selected="selected"';  ?> >Medium</option>
        <option name="large" value="Large" <? if($product->size =="Large") echo 'selected="selected"';  ?> >Large</option>
        <option name="xlarge" value="XLarge" <? if($product->size =="XLarge") echo 'selected="selected"';  ?>>XLarge</option>
    </select><br><br>
    Miktar : <input type="text" name="txtQuantity" value="<?= $product->quantity ?>" /><br><br>
    Renk : <select name="renk">
        <option name="siyah" value="Siyah" <?= $product->color == "Siyah" ?'selected="selected"' : '' ?>>Siyah</option>
        <option name="beyaz" value="Beyaz" <? if($product->color =="Beyaz") echo 'selected="selected"';  ?> >Beyaz</option>
        <option name="sari" value="Sarı" <? if($product->color =="Sarı") echo 'selected="selected"';  ?>>Sarı</option>
        <option name="yesil" value="Yeşil" <? if($product->color =="Yeşil") echo 'selected="selected"';  ?>>Yesil</option>
        <option name="kirmizi" value="Kırmızı" <? if($product->color =="Kırmızı") echo 'selected="selected"';  ?>>Kirmizi</option>
        <option name="mavi" value="Mavi" <? if($product->color =="Mavi") echo 'selected="selected"';  ?> >Mavi</option>
    </select><br><br>
    Fotoğraf linki : <input type="text" name="imgUrl" value="<?= $product->imageurl ?>" /><br><br>
    Ücret : <input type="text" name="price" value="<?= $product->price ?>" /> TL<br><br>
    <input type="submit" value="Kaydet" />
</body>
</html>